# configuration.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-adservice
  namespace: default
  annotations:
    serving.knative.dev/revisionGC: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "15"
        autoscaling.knative.dev/metric: "rps"  
        autoscaling.knative.dev/target: "100"
    spec:
      containerConcurrency: 30
      containers:
      - image: shixiongqi/kn-adservice:v1.0.0
        name: kn-adservice
        ports:
        - name: h2c
          containerPort: 9555
        env:
        # - name: PORT
        #   value: "9555"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        # resources:
        #   requests:
        #     memory: "180Mi"
        #     cpu: "200m"
        #   limits:
        #     memory: "300Mi"
        #     cpu: "300m"
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
---
# SPDX-License-Identifier: MIT
# Copyright (c) 2022 University of California, Riverside

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-cartservice
  namespace: default
  annotations:
    serving.knative.dev/revisionGC: "true"
  
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "15"
        autoscaling.knative.dev/metric: "rps"  
        autoscaling.knative.dev/target: "100"
    spec:
      containerConcurrency: 30
      containers:
      - image: shixiongqi/kn-cartservice:v1.0.0
        name: kn-cartservice
        ports:
        - name: h2c
          containerPort: 7070
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        # resources:
        #   requests:
        #     cpu: 200m
        #     memory: 64Mi
        #   limits:
        #     cpu: 300m
        #     memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]

---
# SPDX-License-Identifier: MIT
# Copyright (c) 2022 University of California, Riverside

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-checkoutservice
  namespace: default
  annotations:
    serving.knative.dev/revisionGC: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "15"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "100"
      
    spec:
      containerConcurrency: 30
      containers:
      - image: shixiongqi/kn-checkoutservice:v1.0.0
        name: kn-checkoutservice
        ports:
        - name: h2c
          containerPort: 5050
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5050"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5050"]
        env:
        # - name: PORT
        #   value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "128.110.96.97:31882"
        - name: SHIPPING_SERVICE_ADDR
          value: "128.110.96.97:31882"
        - name: PAYMENT_SERVICE_ADDR
          value: "128.110.96.97:31882"
        - name: EMAIL_SERVICE_ADDR
          value: "128.110.96.97:31882"
        - name: CURRENCY_SERVICE_ADDR
          value: "128.110.96.97:31882"
        - name: CART_SERVICE_ADDR
          value: "128.110.96.97:31882"
        - name: PRODUCT_CATALOG_SERVICE_URL
          value: "kn-productcatalogservice.default.127.0.0.1.sslip.io"
        - name: SHIPPING_SERVICE_URL
          value: "kn-shippingservice.default.127.0.0.1.sslip.io"
        - name: PAYMENT_SERVICE_URL
          value: "kn-paymentservice.default.127.0.0.1.sslip.io"
        - name: EMAIL_SERVICE_URL
          value: "kn-emailservice.default.127.0.0.1.sslip.io"
        - name: CURRENCY_SERVICE_URL
          value: "kn-currencyservice.default.127.0.0.1.sslip.io"
        - name: CART_SERVICE_URL
          value: "kn-cartservice.default.127.0.0.1.sslip.io"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 64Mi
        #   limits:
        #     cpu: 200m
        #     memory: 128Mi
---
# SPDX-License-Identifier: MIT
# Copyright (c) 2022 University of California, Riverside

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-currencyservice
  namespace: default
  annotations:
    serving.knative.dev/revisionGC: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "15"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "100"
    spec:
      containerConcurrency: 30
      containers:
      - image: shixiongqi/kn-currencyservice:v1.0.0
        name: kn-currencyservice
        ports:
        - name: h2c
          containerPort: 7000
        env:
        # - name: PORT
        #   value: "7000"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"
        - name: DISABLE_STATS
          value: "1"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        # resources:
          # requests:
          #   cpu: 100m
          #   memory: 64Mi
          # limits:
          #   cpu: 200m
          #   memory: 128Mi
---
# SPDX-License-Identifier: MIT
# Copyright (c) 2022 University of California, Riverside

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-emailservice
  namespace: default
  annotations:
    serving.knative.dev/revisionGC: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "15"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "100"
    spec:
      containerConcurrency: 30
      containers:
      - image: shixiongqi/kn-emailservice:v1.0.0
        name: kn-emailservice
        ports:
        - name: h2c
          containerPort: 8080
        env:
        # - name: PORT
        #   value: "8080"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_STATS
          value: "1"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 64Mi
        #   limits:
        #     cpu: 200m
        #     memory: 128Mi
---
# SPDX-License-Identifier: MIT
# Copyright (c) 2022 University of California, Riverside

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-frontend
  namespace: default
  annotations:
    serving.knative.dev/revisionGC: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "2"
        autoscaling.knative.dev/maxScale: "15"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "100"  
    spec:
      containerConcurrency: 100
      containers:
      - image: shixiongqi/kn-frontend:v1.0.0
        name: kn-frontend
        ports:
        - containerPort: 8080
        # readinessProbe:
        #   initialDelaySeconds: 10
        #   httpGet:
        #     path: "/_healthz"
        #     port: 8080
        #     httpHeaders:
        #     - name: "Cookie"
        #       value: "shop_session-id=x-readiness-probe"
        # livenessProbe:
        #   initialDelaySeconds: 10
        #   httpGet:
        #     path: "/_healthz"
        #     port: 8080
        #     httpHeaders:
        #     - name: "Cookie"
        #       value: "shop_session-id=x-liveness-probe"
        env:
        # - name: PORT
        #   value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "128.110.96.97:31882"
        - name: CURRENCY_SERVICE_ADDR
          value: "128.110.96.97:31882"
        - name: CART_SERVICE_ADDR
          value: "128.110.96.97:31882"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "128.110.96.97:31882"
        - name: SHIPPING_SERVICE_ADDR
          value: "128.110.96.97:31882"
        - name: CHECKOUT_SERVICE_ADDR
          value: "128.110.96.97:31882"
        - name: AD_SERVICE_ADDR
          value: "128.110.96.97:31882"
        - name: PRODUCT_CATALOG_SERVICE_URL
          value: "kn-productcatalogservice.default.127.0.0.1.sslip.io"
        - name: CURRENCY_SERVICE_URL
          value: "kn-currencyservice.default.127.0.0.1.sslip.io"
        - name: CART_SERVICE_URL
          value: "kn-cartservice.default.127.0.0.1.sslip.io"
        - name: RECOMMENDATION_SERVICE_URL
          value: "kn-recommendationservice.default.127.0.0.1.sslip.io"
        - name: SHIPPING_SERVICE_URL
          value: "kn-shippingservice.default.127.0.0.1.sslip.io"
        - name: CHECKOUT_SERVICE_URL
          value: "kn-checkoutservice.default.127.0.0.1.sslip.io"
        - name: AD_SERVICE_URL
          value: "kn-adservice.default.127.0.0.1.sslip.io"
        # # ENV_PLATFORM: One of: local, gcp, aws, azure, onprem, alibaba
        # # When not set, defaults to "local" unless running in GKE, otherwies auto-sets to gcp 
        # - name: ENV_PLATFORM 
        #   value: "aws"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_STATS
          value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        # - name: CYMBAL_BRANDING
        #   value: "true"
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 64Mi
        #   limits:
        #     cpu: 200m
        #     memory: 128Mi
---
# SPDX-License-Identifier: MIT
# Copyright (c) 2022 University of California, Riverside

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-paymentservice
  namespace: default
  annotations:
    serving.knative.dev/revisionGC: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "15"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "100"
    spec:
      containerConcurrency: 30
      containers:
      - image: shixiongqi/kn-paymentservice:v1.0.0
        name: kn-paymentservice
        ports:
        - name: h2c
          containerPort: 50051
        env:
        # - name: PORT
        #   value: "50051"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"
        - name: DISABLE_STATS
          value: "1"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 64Mi
        #   limits:
        #     cpu: 200m
        #     memory: 128Mi
---
# SPDX-License-Identifier: MIT
# Copyright (c) 2022 University of California, Riverside

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-productcatalogservice
  namespace: default
  annotations:
    serving.knative.dev/revisionGC: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "15"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "100"
    spec:
      containerConcurrency: 30
      containers:
      - image: shixiongqi/kn-productcatalogservice:v1.0.0
        name: kn-productcatalogservice
        ports:
        - name: h2c
          containerPort: 3550
        env:
        # - name: PORT
        #   value: "3550"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 64Mi
        #   limits:
        #     cpu: 200m
        #     memory: 128Mi
---
# SPDX-License-Identifier: MIT
# Copyright (c) 2022 University of California, Riverside

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-recommendationservice
  namespace: default
  annotations:
    serving.knative.dev/revisionGC: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "15"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "100"
    spec:
      containerConcurrency: 30
      containers:
      - image: shixiongqi/kn-recommendationservice:v1.0.0
        name: kn-recommendationservice
        ports:
        - name: h2c
          containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        env:
        # - name: PORT
        #   value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "128.110.96.97:31882"
        - name: PRODUCT_CATALOG_SERVICE_URL
          value: "kn-productcatalogservice.default.127.0.0.1.sslip.io"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"
        - name: DISABLE_STATS
          value: "1"
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 220Mi
        #   limits:
        #     cpu: 200m
        #     memory: 450Mi
---
# SPDX-License-Identifier: MIT
# Copyright (c) 2022 University of California, Riverside

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-shippingservice
  namespace: default
  annotations:
    serving.knative.dev/revisionGC: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "15"
        autoscaling.knative.dev/metric: "rps"  
        autoscaling.knative.dev/target: "100"  
    

    spec:
      containerConcurrency: 30
      containers:
      - image: shixiongqi/kn-shippingservice:v1.0.0
        name: kn-shippingservice
        ports:
        - name: h2c
          containerPort: 50051
        env:
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 64Mi
        #   limits:
        #     cpu: 200m
        #     memory: 128Mi